name: PlatformIO CI

on: [push]

jobs:
  set-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.set-runner.outputs.runner-label }}

    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .busy == false and .labels[] .name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=ubuntu-latest" >> $GITHUB_OUTPUT
          fi

  checkout:
    needs: set-runner
    runs-on: ${{ needs.set-runner.outputs.runner-label }}
    steps:
      - uses: actions/checkout@v3

  prepare:
    needs: [set-runner, checkout]
    runs-on: ${{ needs.set-runner.outputs.runner-label }}
    steps:
      - name: Dump Runner Label
        env:
          RUNNER_LABEL: ${{ needs.set-runner.outputs.runner-label }}
        run: echo "$RUNNER_LABEL"
      - name: Install Python
        if: needs.check-runner.outputs.runner-label != 'self-hosted'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        if: needs.check-runner.outputs.runner-label != 'self-hosted'
        run: pip install --upgrade platformio

  build:
    needs: [set-runner, prepare]
    runs-on: ${{ needs.set-runner.outputs.runner-label }}
    steps:
      - name: Build PlatformIO Project
        run: pio run
        
  flash-test:
    needs: [set-runner, build]
    runs-on: ${{ needs.set-runner.outputs.runner-label }}
    if: ${{ needs.set-runner.outputs.runner-label }} == "self-hosted"
    steps:
      - name: Upload PlatformIO Project
        run: pio run -t nobuild -t upload -e flashtest
