name: PlatformIO CI

on: [push]

jobs:
  # Check if self-hosted runner is available, else use a Github hosted one
  set-runner:
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{steps.set-runner.outputs.runner-label}}
    steps:
      - name: Set runner
        id: set-runner
        run: |
          runners=$(curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runners")
          available=$(echo "$runners" | jq '.runners[] | select(.status == "online" and .labels[].name == "self-hosted")')
          if [ -n "$available" ]; then
            echo "runner-label=self-hosted" >> $GITHUB_OUTPUT
          else
            echo "runner-label=builtin" >> $GITHUB_OUTPUT
          fi
      - name: Echo runner label
        run: |
          echo "Runner with label ${{needs.set-runner.outputs.runner-label}} is used for subsequent jobs"

  checkout:
    needs: set-runner
    runs-on: ${{needs.set-runner.outputs.runner-label}}
    steps:
      - uses: actions/checkout@v3

  # Github runners need some preparation before executing build
  prepare:
    needs: [set-runner, checkout]
    runs-on: ${{needs.set-runner.outputs.runner-label}}
    if: ${{contains(needs.set-runner.outputs.runner-label, 'builtin')}}
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

  # Compile the SW
  build:
    needs: [set-runner, prepare]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    runs-on: ${{needs.set-runner.outputs.runner-label}}
    steps:
      - name: Build PlatformIO Project
        run: pio run

  # Test if flashing works (only possible with self-hosted runner)
  flash-test:
    needs: [set-runner, build]
    runs-on: ${{needs.set-runner.outputs.runner-label}}
    if: ${{contains(needs.set-runner.outputs.runner-label, 'self-hosted')}}
    steps:
      - name: Upload PlatformIO Project
        run: |
          # Flash two times to make sure we can reflash from current build
          pio run -t nobuild -t upload -e flashtest
          pio run -t nobuild -t upload -e flashtest
